import "./globals.css";
import { Comorant_Garamond, Noto_Sans_JP, Sawarabi } from "@/lib/custom-fonts";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Comorant_Garamond.variable} ${Noto_Sans_JP.variable} ${Sawarabi.variable} no-scrollbar`}
      >
        {children}
      </body>
    </html>
  );
}
